apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: dashgoat
  name: dashgoat
spec:
  endpoints:
  - path: /metrics
    port: http
  namespaceSelector:
    matchNames:
    - dashgoat
  selector:
    matchLabels:
      app: dashgoat
