apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashgoat
  namespace: dashgoat
  labels:
    app: dashgoat
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dashgoat
  template:
    metadata:
      labels:
        app: dashgoat
    spec:
      containers:
      - name: dashgoat
        image: analogbear/dashgoat:1.5.0
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2000
        readinessProbe:
          httpGet:
            path: /health
            port: 2000
          initialDelaySeconds: 5
          periodSeconds : 5
