apiVersion: v1
kind: Service
metadata:
 name: dashgoat-headless-svc
 namespace: dashgoat
spec:
 clusterIP: None
 selector:
   app: dashgoat
 ports:
 - port: 2000
   targetPort: 2000
   protocol: TCP
   name: http
