name: Build and Test dashGoat

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git

    - name: Build binary
      run: make linux

    - name: Copy binary
      run: ./tests/copy-bin.sh

    - name: Start Web Service
      run: ./tests/start-single.sh

    - name: TTL test
      run: ./tests/ttl-test.sh

    - name: Nextupdate test
      run: ./tests/nextupdate-test.sh

    - name: Metrics test
      run: ./tests/metrics-test.sh

    - name: Tags test
      run: ./tests/tags-test.sh

    - name: End test
      run: ./tests/stop-instances.sh
